name       : heroic-games-launcher
version    : 2.2.6
release    : 4
source     :
    - https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/archive/refs/tags/v2.2.6.tar.gz : 2af864007e39796ed985051b392277618400d6edafd4cda0dc04687defbcae2f
homepage   : https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher
license    : GPL-3.0-or-later
component  : games
networking : yes
summary    : An Open Source alternative to the Epic Games Launcher. Also supports GOG store.
description: |
    Heroic is an Open Source Game Launcher for Linux, Windows and MacOS (for both Native and Windows Games using Crossover). Right now it supports launching games from the Epic Games Store using Legendary and GOG Games using our custom implementation with gogdl. Heroic is built with Web Technologies like: TypeScript, React, NodeJS and Electron.
builddeps  :
    - yarn
setup      : |
    yarn install
build      : |
    yarn dist tar.xz
install    : |
    export heroicdir=/usr/share/heroic
    install -dm00755 $installdir/$heroicdir
    install -dm00755 $installdir/usr/bin

    # Copy dist files and link binaries
    cp -R ./dist/linux-unpacked/* $installdir/$heroicdir/
    ln -s $heroicdir/heroic $installdir/usr/bin/heroic
    ln -s $heroicdir/resources/app.asar.unpacked/build/bin/linux/legendary $installdir/usr/bin/legendary
    ln -s $heroicdir/resources/app.asar.unpacked/build/bin/linux/gogdl $installdir/usr/bin/gogdl

    # Copy icon
    install -Dm00644 ./dist/linux-unpacked/resources/app.asar.unpacked/build/icon.png $installdir/usr/share/icons/hicolor/512x512/apps/heroic.png

    # Set up .desktop file
    install -Dm00644 $pkgfiles/heroic.desktop $installdir/usr/share/applications/heroic.desktop
