name       : heroic-games-launcher
version    : 2.1.1
release    : 1
source     :
    - https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/archive/refs/tags/v2.1.1.tar.gz : 2440ca9b3ddf53fd60c5c7f7f7e48cbf3731bbf229c4720bf4e7ab1050284ca3
license    : GPL-3.0-or-later
component  : games
networking : yes
summary    : An Open Source alternative to the Epic Games Launcher.
description: |
    Heroic is an Open Source Game Launcher for Linux, Windows and MacOS (for both Native and Windows Games using Crossover). Right now it supports launching games from the Epic Games Store using Legendary, a CLI alternative to the Epic Games Launcher. Heroic is built with Web Technologies like: TypeScript, React, NodeJS and Electron.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(atk)
    - pkgconfig(atk-bridge-2.0)
    - pkgconfig(atspi-2)
    - pkgconfig(cairo)
    - pkgconfig(gbm)
    - pkgconfig(gdk-pixbuf-2.0)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libdrm)
    - pkgconfig(pango)
    - pkgconfig(xcomposite)
    - pkgconfig(xdamage)
    - pkgconfig(xfixes)
    - pkgconfig(xkbcommon)
    - pkgconfig(xrandr)
    - pkgconfig(xshmfence)
    - cups-devel
    - git
    - yarn
setup      : |
    yarn install
build      : |
    yarn dist tar.xz
install    : |
    export heroicdir=/usr/share/heroic
    install -dm00755 $installdir/$heroicdir
    install -dm00755 $installdir/usr/bin

    # Copy dist files and link binaries
    cp -R ./dist/linux-unpacked/* $installdir/$heroicdir/
    ln -s $heroicdir/heroic $installdir/usr/bin/heroic
    ln -s $heroicdir/resources/app.asar.unpacked/build/bin/linux/legendary $installdir/usr/bin/legendary

    # Copy icon
    install -Dm00644 ./dist/linux-unpacked/resources/app.asar.unpacked/build/icon.png $installdir/usr/share/icons/hicolor/512x512/apps/heroic.png

    # Set up .desktop file
    install -Dm00644 $pkgfiles/heroic.desktop $installdir/usr/share/applications/heroic.desktop